Submitted by: Marielle Alexa A. Salvador

Loading Data Into Python

In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')
print (data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [ ]:
print(type(data))

<class 'numpy.ndarray'>


Data Type

In [ ]:
print(data.dtype)


float64


In [ ]:
print(data.shape)

(60, 40)


In [ ]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [ ]:
print('middle value in data:', data[29, 19])

middle value in data: 16.0


Slicing Data

In [ ]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [ ]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [ ]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


Analyzing the Data

In [ ]:
print(np.mean(data))

6.14875


In [ ]:
#not all functions have input that's why
import time
print(time.ctime())

Tue Aug 19 01:34:26 2025


In [ ]:
maxval, minval, stdval = np.amax(data), np.amin(data), np.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [ ]:
#0 will be on the first axis (rows), while everything on the second (columns)
patient_0 = data[0, :]
print('maximum inflammation for patient 0:', np.amax(patient_0))

maximum inflammation for patient 0: 18.0


In [ ]:
print('maximum inflammation for patient 2:', np.amax(data[2, :]))

maximum inflammation for patient 2: 19.0


In [ ]:
print(np.max(data, axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [ ]:
print(np.max(data, axis=1).shape)

(60,)


In [ ]:
print(np.mean(data, axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [ ]:
print(np.mean(data, axis=0).shape)

(40,)


In [ ]:
print(np.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


Slicing Strings

In [ ]:
#challenge
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [ ]:
#this will answer what is value of element[:4]? what about element[4:]? Or element[:]?
print ('element[:4]:', element[:4])
print ('element[4:]:', element[4:])
print ('element[:]:', element[:])

element[:4]: oxyg
element[4:]: en
element[:]: oxygen


In [ ]:
#continuation
print ('element [-1]:', element [-1])
print ('element [-2]:', element [-2])


element [-1]: n
element [-2]: e


In [ ]:
print ('element[1:-1]:', element[1:-1])

element[1:-1]: xyge
